### ISSUE TITLE
Food Waste

### ISSUE THREAD

**Issue by HProsperouS** [green-mile/green-mile#4]
There are existing applications we are refer to:
NoWaste, NOWASTE is a food inventory app where you can easily track, organize and manage the food in your fridge. You can check what food you have left, see what food you need to use first, plan your meals and create a shopping list, all to avoid unnecessary purchases while reducing food waste. https://www.nowasteapp.com/ 
OLIO - Share more. Waste less. OLIO connects neighbours with each other and with local businesses so surplus food can be shared, not thrown away. This could be food nearing its sell-by date in local stores, spare home-grown vegetables, bread from your baker, or the groceries in your fridge when you go away. For your convenience, OLIO can also be used for non-food household items, too.https://olioex.com/about/#about 
Too Good To Go, an app operating in the UK, allows users to order leftover food at a discount from restaurants, according to the website. The goal is to help curb waste from establishments that typically toss out perfectly edible food at the end of the day.https://www.businessgreen.com/interview/2467195/too-good-to-go-how-a-phone-app-is-helping-restaurants-sell-their-leftover-food 
https://language.chinadaily.com.cn/2016-08/24/content_26559200.htm 

More Application of mitigation of food waste refer to here:
https://www.weforum.org/agenda/2022/06/reduce-food-waste-apps-smartphones/ 

Our aim is to combine the good features of all these apps and make it a better one  
@lx0f @Ronandt @Zhe-Yin @NightmareWaifu

**Comment by lx0f** [comment]
Sounds interesting. You know what I kinda like it. So we're kinda of pushing a "Sell excess food at a discounted rate" agenda to local food businesses and providing an easy platform for it.

Its simple and effective! Now we just need to figure out:
- How do we convince local food businesses to use our platform?
- How can the platform be designed such that integration with local food businesses is seamless? (inventory issue as stated by @Ronandt)
- Who will buy the excess food?
- How will the food end up in the hands of the consumers?
- etc...

I'm onboard with this 🙌 Hopefully the solution can be an effective food waste mitigation platform for SG

**Comment by HProsperouS** [comment]
In my opinion, local food businesses have their own track system to check if it is expired soon, and it is hard for them too use our application to check inventory as they have to upload multiple times since they have a huge stock. So what we need to do is to create a platform something like carousell to allow them to upload their product and sell it

**Comment by HProsperouS** [comment]
This market, in my opinion, still has a bright future. There has never been a company in Singapore that has attempted to sell expired soon food（except the one selling chocolate at 1 dollar shop）, which is undoubtedly beneficial to some low-income families. Some c ompanies can also be benefitted. for example, they provide employee meals. Their food demand is high. At the same time, they can digest foods that are about to expire in a short period of time. At the same time, they can digest foods that are about to expire in a short period of time.  
The problem we faced now is How to Persuade people  Food is safe and encourage them to buy, and what we will allow certain types of food to be sold on our platform, as well as how to ensure food safety in order to ensure what we sell don't cause risks.

**Comment by Zhe-Yin** [comment]
For all the expiring food like can goods , we can mainly target the low-income families they are usually the most willing to purchase food at this low price nearing expired date. Usually dry goods and those can goods are best before soo they can last another week or 2 before it actually spoils.
