### ISSUE TITLE
RFC: Food & Excess Manager

### ISSUE THREAD

**Issue by lx0f** [green-mile/green-mile#5]
**Context**
Sustainable living tries to reduce carbon emissions and embrace sustainability by recycling more and taking public transport. The key pillars are the Circular Economy, Eco Stewardship Programme and Green Commutes. 
We will reduce carbon emissions and embrace sustainability by consuming less, recycling more, and taking public transport. We will also work towards our vision of becoming a Zero Waste Nation powered by a circular economy, with “Reduce, Reuse and Recycle” as a norm for citizens and businesses.

Sustainable consumption is part of sustainable living as it aims to reduce food wastage through reusing and reducing. Currently, the Singapore Government aims to do this by batling food wastage.

Food wastage is greatly increasing due to the population and generally causes wasted water to be used for potentially wasted food and causes a larger carbon footprint. This contributes to climate change and global warming which is what sustainable living is trying to combat. 

If we reduce food wastage, there would be less demand for food as well which would have fewer resources wasted on food overall.

**Problems faced regarding these topics (Food wastage)**
-Businesses might not be accurately keeping their inventory in check and their expiry times. This leads to potentially thrown-away food. Businesses also waste costs.
-Families can also have trouble keeping track of food expiry times this also leads to wasted food and wasted money and is especially critical for lower SES families
-Families don't have a centralised easy way to keep track of what is in their inventory as well
-Some families don’t care about it as they are not aware that wasting food causes a huge impact on the environment
-Some people have a hard time controlling themselves in overspending on food as well and keep on purchasing unnecessary stuff and not on the things they need
-Some people cannot afford food easily as Singapore is an expensive place. 
-Even with all these measures, some people still overestimate what they can consume overall

**The solution to the problems**
The main idea is a food management system that keeps track of what you have in the fridge (And you can have one family household account), the expiry times as well as an inbuilt shopping list that prevents overspending. The website can also show the impact that you have made on climate change to have a sense of progress and encouragement. In order to further mitigate wasted food, people can give away items that they don’t really need or that are close to expiry but they can’t consume by another person for collection and provide incentives for the food they donated.

**Why this solves the problem**
This solves the problem as this food management system reduces the amount of food wastage in the system. It also ensures that it gives an opportunity for food to be used no matter what.

**Comment by NightmareWaifu** [comment]
What do we plan on doing when we collecting food that is about to expire/expiring?
I'm thinking we could repurpose them into other uses such as fertilizer etc...

**Comment by Zhe-Yin** [comment]
Ye. Food that has totally expired can be turned into fertilizer. Good idea. We can set up another part where ppl has food that has already expired and we can use it for that purpose also.

**Comment by Zhe-Yin** [comment]
Pain points / Drawbacks .
Food collection stations, onboarding process for businesses ("...small businesses don't either have it (inventory management) or it's very primitive - @D ), food quality , providing value to business / consumers

**Comment by lx0f** [comment]
Great ideas guys, will add them onto the rfc tomorrow! This issue has migrated to Green Mile RFCs PR [#1](https://github.com/green-mile/rfcs/pull/1)

**Comment by NightmareWaifu** [comment]
Logistics of Composting food waste(turning food waste into fertilizer):
We dedicate a department which collects or takes the food from what we have already collected, that is not safe for consumption anymore, and transport them to local composting companies
